### PR TITLE
Use closed_at for PR changelog date check

### PR DESCRIPTION
**Pull request by Tybot204**
Fixes issues #128 and #181 .

It appears GitHub is not consistent on the datetime a PR was closed vs merged at. `closed_at` has always been the same or a second or two later than `merged_at` in my experience with the API. I believe `closed_at` is a more consistent way to gather PRs merged for a given tag when generating release notes.

I'm not confident about this change however. This method looks like it's only used for filtering issues, not PRs. I found no other place we use `merged_at` other than to check if a PR was closed without merging.

### CODE REVIEW

**Comment by idlem1nd** [comment]
Surely closed and merged are separate states? A merged PR isn't necessarily closed. And you can close a PR without merging it...

**Comment by Tybot204** [comment]
@idlem1nd I believe merging a PR automatically closes it. Is there a way to merge without closing? A PR can definitely be closed without merging though.

GREN already filters PRs that have not been merged from release notes by using `merged_at`. After that it filters by `merged_at` date, which I think should just use `closed_at` instead since we already know the PR is merged. Closed seems to be the final state in GitHub, as it takes a second or so to finally transition there.

**Comment by idlem1nd** [comment]
@Tybot204 yes looks like you're right - merged PRs are closed.

**Comment by idlem1nd** [comment]
Will this fix #181 ?

**Comment by Tybot204** [comment]
@idlem1nd I believe so. As far as I can tell it's the same underlying cause. I'll update the PR description to include that issue.

**Comment by alexcanessa** [comment]
@all-contributors please add @Tybot204 for code

**Pull request merged**
