### PR TITLE
[Bugfix] Some Pull Requests/Issues/CommitBlocks are missing when generating release notes

### PR DESCRIPTION
**Pull request by monicarib**
## Issue Description

When running the command: `gren release` to generate the release notes, the last resource (PR, issue, commit block) was not included on the list.

Let's suppose that your data source is Pull Requests. 
You open two pull requests, tag them (one as bug, and the other as enhancement), and merge them into master. After creating your release and tag on GitHub, if you generate the notes for the release, the last PR merged was not added into it, and the last PR of the release before (that was not included before) was also, incorrectly, added.

## Issues Related
#128 

## Solution

When getting the actual date of creation of the tag, it was considering the date of last commit of the tag. The solution was to consider the creation date of the release.

### CODE REVIEW

**Comment by alexcanessa** [comment]
That's great, thanks @monicarib

**Comment by alexcanessa** [comment]
@all-contributors please add @monicarib for code

**Comment by monicarib** [comment]
@alexcanessa thank you!
Could you generate a new release with this update?

**Comment by alexcanessa** [comment]
@monicarib yup, will do this evening

**Comment by alexcanessa** [comment]
Still some testing happening. Not sure if this is gonna work when no releases are present.

**Comment by monicarib** [comment]
@alexcanessa do you have a specific scenario? We could add more unit test to make sure everything is fine.

**Comment by JHFarrant** [comment]
@alexcanessa @monicarib Great fix here :) 
Do we know when this will be released? Can I help at all with testing?

I thought the whole point is this tool lets us release fast? 😉 :trollface:

**Comment by yogevyuval** [comment]
+1 for making a new release so we can use it.
Note: I tried to build it myself with the master, and I get no changelog and it says 0 Pull requests found... Maybe an issue with the current version?
@alexcanessa @monicarib

**Pull request merged**
