### PR TITLE
Add feature to set limit in options for tags. Fixes #144

### LINKED ISSUE #144: Feature to be able to specify limit on tags for the changelog
I want to be able to run:

    gren changelog --limit-tags=30

Generating the release for just the 30 latest releases, so I don't get a huge file after some months of continuous development.

The feature should add a template string on the bottom of the changelog, like: "To see the full list" -> Point to releases

### PR DESCRIPTION
**Pull request by phun-ky**

### CODE REVIEW

**Comment by alexcanessa** [comment]
@phun-ky any updates on this one? Would really like to merge this 👍

**Comment by phun-ky** [comment]
@alexcanessa oh, I totally forgot this! Will try to squeeze it in tonight :) (CET)

**Comment by phun-ky** [comment]
@alexcanessa sorry for the slow-mo here :(

**Comment by phun-ky** [comment]
@alexcanessa seems that my prettierconfig was activated there.. bah! will try to fix it

**Comment by alexcanessa** [comment]
@phun-ky should be easy to fix as you run `gulp` it should run the `eslint` configuration.

**Comment by phun-ky** [comment]
@alexcanessa done

**Comment by alexcanessa** [comment]
Nice!

`gren` has to be upgraded a bit in terms of stack TBH. e.g. `hooks` with `npm` tasks instead of `gulp`, `Prettier` with `eslint` (with no configuration) etc.

**Comment by alexcanessa** [comment]
@all-contributors add code for @phun-ky

**Comment by alexcanessa** [comment]
Oops, the other way around lol

@all-contributors add @phun-ky for code

**Pull request merged**
